### PR TITLE
Update example for iOS/Android + RN 0.14.2

### PR DESCRIPTION
**Pull request by rreusser**
Okay, none of the example code itself changed, but I recreated the everything around it using `react-native-cli@0.1.7` + RN 0.14.2. iOS and Android both run fine for me.

I think that's everything. Will test with RN 0.15.x and confirm that it's still good to go. Looks like I must just have some nagging oversight in my app such that it doesn't work.

I gitignored the build files, but let me know if anything needs cleanup or changes! Thanks!

### CODE REVIEW

**Comment by rreusser** [comment]
(Current example was

```
  "dependencies": {
    "react-native": "^0.3.10",
    "react-native-linear-gradient": "^0.1.7"
  }
```

so I figured maybe it wasn't so extreme to recreate.)

**Comment by nickhudkins** [comment]
I'll get this merged in :) not extreme at all!

**Comment by brentvatne** [comment]
I updated the example to 0.16.0 last night and linear-gradient#master :dancer:

**Comment by rreusser** [comment]
Awesome, thanks! FYI: The simple example always worked, but we ran into some problems on Android in which the gradient rendered one time but then usually seemed to just show a solid semi-transparent color. It's quite possibly our fault but I wasn't able to find a simple example that didn't always work. At any rate, we put Android on hold since everything we need is… forthcoming. If I find any simple reproducible examples though, I'll let you know!

**Pull request closed without merging**
